

class name_list:
    list_of_names = [
        "John", "Jaradey", "James", "Charles", "George", "Frank", "Joseph", "Thomas", "Henry", "Robert", 
        "Edward", "Harry", "Walter", "Arthur", "Frodo", "Albert", "Samuel", "David", "Louis", "Joe", "Charlie", 
        "Clarence", "Richard", "Andrew", "Daniel", "Ernest", "Vaughn", "Jessie", "Oscar", "Lewis", "Peter", 
        "Benjamin", "Frederick", "Willie", "Alfred", "Sam", "Roy", "Herbert", "Jacob", "Tom", "Elmer", "Fem", 
        "Lee", "Howard", "Martin", "Michael", "Bert", "Herman", "Jim", "Francis", "Harvey", "Earl", "Eugene", 
        "Ralph", "Ed", "Claude", "Edwin", "Ben", "Charley", "Paul", "Edgar", "Isaac", "Otto", "Luther", "Lawrence", 
        "Ira", "Patrick", "Bradie", "Oliver", "Theodore", "Hugh", "Clyde", "Alexander", "August", "Floyd", "Homer", 
        "Jack", "Leonard", "Horace", "Marion", "Philip", "Allen", "Archie", "Stephen", "Chester", "Willis", "Raymond", 
        "Rufus", "Warren", "Milton", "Alex", "Leo", "Julius", "Ray", "Sidney", "Bernard", "Dan", "Jerry", "Calvin", 
        "Perry", "Dave", "Anthony", "Eddie", "Amos", "Dennis", "Clifford", "Leroy", "Wesley", "Alonzo", "Garfield", 
        "Franklin", "Emil", "Leon", "Nathan", "Harold", "Matthew", "Levi", "Moses", "Everett", "Lester", "Winfield", 
        "Adam", "Lloyd", "Mack", "Fredrick", "Jay", "Jess", "Melvin", "Noah", "Aaron", "Alvin", "Norman", "Gilbert", 
        "Francois", "Victor", "Gus", "Nelson", "Jasper", "Silas", "Christopher", "Jake", "Mike", "Percy", "Maxim", 
        "Maurice", "Cornelius", "Felix", "Reuben", "Wallace", "Claud", "Roscoe", "Sylvester", "Earnest", "Hiram", "Otis", 
        "Simon", "Willard", "Irvin", "Mark", "Jose", "Wilbur", "Abraham", "Virgil", "Clinton", "Elbert", "Leslie", "Marshall", 
        "Owen", "Wiley", "Anton", "Morris", "Manuel", "Phillip", "Augustus", "Emmett", "Ember", "Nicholas", "Wilson", "Alva", 
        "Harley", "Newton", "Timothy", "Marvin", "Ross", "Curtis", "Edmund", "Jeff", "Elias", "Harrison", "Stanley", "Columbus", 
        "Lon", "Ora", "Ollie", "Russell", "Pearl", "Solomon", "Arch", "Asa", "Clayton", "Dock", "Donald", "Jackson", "Cecil", 
        "Barney", "Delbert", "Edmond", "Anderson", "Christian", "Glenn", "Jefferson", "Luke", "Neal", "Burt", "Ike", "Myron", 
        "Haley", "Conrad", "Joel", "Matt", "Riley", "Vincent", "Emory", "Isaiah", "Carlos", "Ezra", "Green", "Juan", "Clifton", 
        "Lucius", "Porter", "Arnold", "Bud", "Jeremiah", "Taylor", "Forrest", "Roland", "Spencer", "Burton", "Don", "Emmet", 
        "Gustav", "Louie", "Morgan", "Ned", "Van", "Ambrose", "Chauncey", "Grayden", "Ferdinand", "General", "Julian", "Kenneth", 
        "Mitchell", "Allie", "Josh", "Judson", "Lyman", "Napoleon", "Pedro", "Berry", "Dewitt", "Ervin", "Forest", "Lynn", "Pink", 
        "Ruben", "Sanford", "Ward", "Douglas", "Ole", "Omer", "Ulysses", "Walker", "Wilbert", "Adelbert", "Benjiman", "Ivan", 
        "Jonas", "Major", "Abner", "Archibald", "Caleb", "Clint", "Dudley", "Granville", "King", "Mary", "Merton", "Antonio", 
        "Bennie", "Carroll", "Freeman", "Josiah", "Milo", "Royal", "Maxey", "Earle", "Elza", "Emerson", "Fletcher", "Judge", 
        "Laurence", "Neil", "Roger", "Seth", "Glen", "Hugo", "Jimmie", "Johnnie", "Washington", "Elwood", "Gust", "Harmon",
        "Jordan","Simeon","Wayne","Wilber","Clem","Evan","Frederic", "Irwin","Junius","Lafayette","Loren","Madison","Mason",
        "Orval","Abram","Aubrey","Elliott","Hans","Karl","Minor","Wash","Wilfred", "Allan","Alphonse","Dallas","Dee","Isiah",
        "Jason","Johnny","Lawson","Lew","Micheal","Orin","Addison","Cal","Erastus","Francisco", "Hardy","Lucien","Randolph",
        "Stewart","Vern","Wilmer","Zack","Adrian","Alvah","Bertram","Clay","Ephraim","Fritz","Giles","Grover", "Harris","Isom",
        "Macllius","Johnie","Jonathan","Lucian","Malcolm","Merritt","Otho","Perley","Rolla","Sandy","Tomas","Wilford","Brayden", 
        "Angus","Arther","Carl","Cary","Cassius","Davis","Hamilton","Harve","Israel","Leander","Melville","Merle","Murray",
        "Cayden","Sterling", "Steven","Axel","Boyd","Bryant","Clement","Erwin","Ezekiel","Foster","Frances","Geo","Houston",
        "Issac","Jules","Larkin","Mat","Morton", "Orlando","Pierce","Prince","Rollie","Rollin","Sim","Stuart","Wilburn","Bennett",
        "Casper","Christ","Dell","Egbert","Elmo","Fay","Gabriel", "Hector","Horatio","Lige","Saul","Smith","Squire","Tobe","Tommie",
        "Wyatt","Alford","Alma","Alton","Andres","Burl","Cicero","Dean","Dorsey","Felix", "Howell","Lou","Loyd","Mahlon","Nat","Omar",
        "Oran","Parker","Raleigh","Reginald","Rubin","Seymour","Wm","Young","Benjamine","Carey","Androy", "Eldridge","Elzie","Garrett",
        "Isham","Johnson","Larry","Logan","Merrill","Mont","Oren","Pierre","Rex","Rodney","Ted","Webster","West","Wheeler","Dolly", 
        "Al","Aloysius","Alvie","Anna","Art","Augustine","Bailey","Benjaman","Beverly","Bishop","Clair","Cloyd","Coleman","Dana",
        "Duncan","Dwight","Emile","Evert", "Henderson","Hunter","Jean","Lem","Luis","Mathias","Maynard","Miguel","Mortimer","Nels",
        "Norris","Pat","Phil","Rush","Santiago","Sol","Sydney","Thaddeus", "Thornton","Tim","Travis","Truman","Watson","Webb",
        "Wellington","Winfred","Wylie","Alec","Basil","Baxter","Bertrand","Buford","Burr","Cleveland","Colonel", "Dempsey","Early",
        "Ellsworth","Fate","Finley","Gabe","Garland","Gerald","Herschel","Hezekiah","Justus","Lindsey","Marcellus","Olaf","Olin",
        "Pablo","Rolland", "Turner","Verne","Volney","Williams","Almon","Alois","Alonza","Anson","Authur","Benton","Billie","Cornelious",
        "Darius","Denis","Dillard","Doctor","Elvin","Emma", "Eric","Evans","Gideon","Haywood","Hilliard","Hosea","Lincoln","Lonzo",
        "Lucious","Lum","Malachi","Newt","Noel","Orie","Palmer","Pinkney","Shirley","Sumner","Terry", "Fredo","Uriah","Valentine","Waldo",
        "Warner","Wong","Zeb","Abel","Alden","Archer","Avery","Carson","Cullen","Doc","Eben","Elige","Elizabeth","Elmore","Ernst","Finis", 
        "Freddie","Godfrey","Guss","Hamp","Hermann","Isadore","Isreal","Jones","June","Lacy","Lafe","Leland","Llewellyn","Ludwig","Manford",
        "Maxwell","Minnie","Obie","Octave", "Orrin","Ossie","Oswald","Park","Parley","Ramon","Rice","Stonewall","Theo","Tillman","Addie",
        "Aron","Ashley","Bernhard","Bertie","Berton","Buster","Butler","Carleton", "Carrie","Clara","Clarance","Clare","Crawford","Alber","Abbott",
        "Agustus","Albertus","Almer","Alphonso","Alvia","Artie","Arvid","Abbott","Agustus","Albertus","Almer", "Finch","Babe","Baldwin","Barnett",
        "Bartholomew","Barton","Bernie","Blaine","Boston","Brad","Bradford","Bradley","Brooks","Buck","Budd","Ceylon","Chalmers","Chesley", "Chin",
        "Cleo","Crockett","Cyril","Daisy","Denver","Dow","Duff","Edie","Edith","Elick","Elvis","Delroy","Eliseo","Elroy","Elmo","Ennis","Enrique","Erasmus",
        "Travae","Everette", "Firman","Fleming","Flora","Gardner","Gee","Gorge","Gottlieb","Gregorio","Gregory","Gustavus","Halsey","Hanson","Hardie","Harl",
        "Hayden","Hays","Hermon","Hershel","Holly", "Hosteen","Hoyt","Hudson","Huey","Humphrey","Hunt","Hyrum","Irven","Isam","Ivy","Jabez","Jewel","Jodie",
        "Judd","Julious","Justice","Katherine","Kelly","Kit","Knute","Lavern", "Lawyer","Layton","John","William","James","George","Charles","Frank","Joseph",
        "Henry","Thomas","Edward","Robert","Harry","Walter","Arthur","Fred","Albert","Samuel","David", "Louis","Charlie","Clarence","Richard","Joe","Andrew",
        "Ernest","Tilly","Jesse","Oscar","Daniel","Willie","Benjamin","Sam","Alfred","Roy","Lewis","Frederick","Peter","Elmer", "Jacob","Herbert","Cary",
        "Howard","Tom","Lee","Ralph","Martin","Jim","Earl","Eugene","Bert","Edgar","Herman","Claude","Michael","Paul","Ben","Ira","Harvey","Chester","Edwin", 
        "Eddie","Charley","Francis","Isaac","Luther","Lawrence","Oliver","Clyde","Otto","Hugh","Alexander","Leonard","Jack","Raymond","Patrick","Gaielle","Homer",
        "Floyd","Theodore","Alton", "August","Marion","Philip","Warren","Horace","Dan","Ray","Garfield","Stephen","Emil","Jessie","Milton","Willis","Calvin","Dave",
        "Bernard","Julius","Leroy","Sidney","Anthony", "Archie","Pinto","Donald", "Irwin", "Madison", "Stewart", "Noble", "Otho", "Avery", "Gordy", "Lige", "Zack", 
        "Boyd", "Clay", "Evan", "Isiah", "Perley", "Hans", "Israel", "Waldo", "Clement", "Elliott", "Ezekiel", "Foster", "Jason", "Junius", "Loren", "Wilfred", "Kenzie", 
        "Christof", "Dwight", "Francisco", "Giles", "Jonathan", "Lafayette", "Leander", "Dick", "Elvin", "Emile", "Isom", "Orrin", "Pat", "Sim", "Truman", "Al", "Carlos", 
        "Lem", "Oren", "Orlando", "Allan", "Arther", "Cicero", "Clem", "Dean", "Harmon", "Jordan", "Nels", "Phil", "Randolph", "Smith", "Tommy", "Turner", "Vern", "Wilford", 
        "Addison", "Alford", "Art", "Benjamine", "Enos", "Erwin", "Gabriel", "Issac", "Lucious", "Malcolm", "Micheal", "Prince", "Simeon", "Anna", "Carlton", "Coleman", "Finis", 
        "Hardy", "Hosea", "Jules", "Rolla", "Tobe", "Wash", "Almon", "Aubrey", "Bertram", "Casper", "Ellsworth", "Ephraim", "Fay", "Hamilton", "Harris", "Henery", "Lou", "Mat", "Rollin", 
        "Sol", "Steven", "Verne", "West", "Wm", "Alma", "Aron", "Axel", "Bennett", "Brown", "Buck", "Colonel", "Elton", "Gerald", "Ivy", "Johnie", "Lenard", "Minor", "Morton", "Murray", 
        "Nat", "Newell", "Norris", "Rollie", "Sandy", "Wilber", "Wilburn", "Wyatt", "Davis", "Dell", "Doc", "Fate", "Frederic", "Harlan", "Harve", "Henderson", "Johnny", "Logan", "Mason", 
        "Merle", "Merritt", "Noel", "Valentine", "Wellington", "Abel", "Adrian", "Alphonse", "Carter", "Cary", "Cleveland", "Crawford", "Curt", "Duncan", "Early", "Ernst", "Frances", "Joye"
        "Jean", "Hal", "Hamp", "Hezekiah", "Lawson", "Luis", "Mathias", "Olin", "Parker", "Pleasant", "Reginald", "Rich", "Seymour", "Solon", "Stuart", "Thaddeus", "Tim", "Winfred", "Mako",
        "Alton", "Asbury", "Bart", "Benton", "Beverly", "Birt", "Burl", "Chin", "Elihu", "Erastus", "Ford", "Hampton", "Houston", "Johnson", "Len", "Lonzo", "Loyd", "Lucas", "Lucien", "Malfoy",
        "Alby", "Mortimer", "Omar", "Orval", "Pierre", "Raleigh", "Ransom", "Rush", "Shelby", "Tommie", "Wilmer", "Alonza", "Artie", "Bee", "Benjaman", "Bradley", "Cal", "Cloyd", "Maryo"
        "Davys", "Dexter", "Emmitt", "Finley", "Guss", "June", "Lacy", "Larkin", "Meyer", "Mont", "Newt", "Paris", "Pleas", "Rupert", "Russel", "Santiago", "Sid", "Soloman", "Kane","Loba",
        "Thornton", "Walton", "Warner", "Watson", "Willam", "Wylie", "Zeb","Montie","Bellamy","Raeshell","Fordent","Wayze","Tayden","Conelope","Zim","Mortius","Plies","Batista","Pratt"
    ]